### ISSUE TITLE
Import the Ponify music archive

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#100]
#91 and #9 must be completed before this. Review this task in more detail with Squirrel.

We have the Ponify music archive sitting on our servers now. This task entails writing and running the scripts to import it into Pony.fm's collection, as well as de-duplicating the Pony.fm library.
## Part 1: Importing the Ponify library

This component of the task is about bringing the Ponify library into Pony.fm so that tagging/classification work can continue on it. Basic efforts should be made to detect and handle duplicate tracks, as follows, but the bulk of the de-duplication effort falls under Part 2 of this task:
- Track ID's for duplicate tracks must not change in order to preserve functioning URL's.
- [x] Hash the audio stream in every file as a means of detecting duplicates.
- [x] Even if a duplicate copy of a track is ignored, the tags should be parsed out of any Ponify files and used to fill in missing data in Pony.fm's database.
- [x] If Pony.fm already has the same track from the MLPMA (recorded in the `mlpma_tracks` table), it should be replaced with the Ponify version (depends on #9) if we have a higher quality version.
- [x] If Pony.fm's existing version of the track was directly uploaded by the artist, whichever version is lossless should be preserved (if neither is lossless, then Pony.fm's existing copy should be kept).
## Part 2: De-duplicating Pony.fm's library

This process has three goals:
- find which tracks we have more than one copy of
- for any tracks with duplicates, find which version has the highest-quality master file
- combine the Pony.fm, MLPMA, Ponify, and PonyvilleFM archives

Modifying/correcting metadata is outside the scope of this component. That will be handled in parallel in #91. De-duplication of Pony.fm's library will happen as follows:
- [ ] prepare a dump of Pony.fm's master audio files, named using their track ID's
- [ ] combine the Pony.fm dump with PonyvilleFM's archive
- [ ] find duplicate tracks in the combined dump and mark which one is the best-quality version
- [ ] re-upload any track master files for which a higher-quality version was found in the combined dump
- [ ] add any new tracks from the combined dump to Pony.fm
- [ ] process the list of duplicate tracks to "merge" duplicate track records on Pony.fm (set up 301 redirects to the oldest instance of the track)
